name: CDK destroy action
description: Destroy CDK app
inputs:
  cdk-folder-name:  
    description: 'where cdk app resides'
    required: true
  stage-name:  
    description: 'stage-name which is used as CDK context var'
    required: true

runs:
  using: "composite"
  steps:
    - name: CDK destroy
      shell: bash
      run: |
        cd ${{ inputs.cdk-folder-name }}
        cdk destroy --context stage-name=${{ inputs.stage-name }} --force
