{
 "title": "Cloudwatch Logs with Alert Events",
 "description": "Cloudwatch logs dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "log_group", "label": "Log Group", "query": "<<LOG_GROUP_NAME>>" },
   {
    "name": "resource_type",
    "label": "Resource Type",
    "query": "glue_jobs,glue_workflows,glue_crawlers,glue_catalogs,lambda_functions,step_functions,emr_serverless,glue_data_quality"
   },
   { "name": "event_result", "label": "Event Result", "query": "INFO,SUCCESS,FAILURE" },
   { "name": "event_status", "label": "Event Status" },
   { "name": "resource_name", "label": "Resource Name" }
  ]
 },
 "panels": [
  {
   "title": "Total events",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": { "LogGroupName": "<<LOG_GROUP_NAME>>" },
     "expression": "| stats count(*) \r\n| filter resource_type IN [${resource_type:doublequote}]\r\n| filter resource_name like /(?i)$resource_name/\r\n| filter event_status like /(?i)$event_status/",
     "logGroups": [
      { "accountId": "<<ACCOUNT_ID>>", "arn": "<<LOG_GROUP_ARN>>", "name": "<<LOG_GROUP_NAME>>" }
     ],
     "metricEditorMode": 1,
     "metricName": "IncomingLogEvents",
     "metricQueryType": 1,
     "namespace": "AWS/Logs",
     "queryMode": "Logs",
     "region": "default",
     "sqlExpression": "| stats count(*) by $resource_type",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Event Result Distribution",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 10, "x": 4, "y": 0 },
   "targets": [
    {
     "dimensions": { "LogGroupName": "<<LOG_GROUP_NAME>>" },
     "expression": "| stats count(*) as cnt by event_result\r\n| filter resource_type IN [${resource_type:doublequote}]\r\n| filter resource_name like /(?i)$resource_name/\r\n| filter event_status like /(?i)$event_status/\r\n| sort by event_result\r\n",
     "logGroups": [
      { "accountId": "<<ACCOUNT_ID>>", "arn": "<<LOG_GROUP_ARN>>", "name": "<<LOG_GROUP_NAME>>" }
     ],
     "metricEditorMode": 1,
     "metricName": "IncomingLogEvents",
     "metricQueryType": 1,
     "namespace": "AWS/Logs",
     "queryMode": "Logs",
     "region": "default",
     "sqlExpression": "| stats count(*) by $resource_type",
     "statistic": "Average",
     "statsGroups": [ "event_result" ]
    }
   ]
  },
  {
   "title": "Events timeline",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Log events",
     "dimensions": { "LogGroupName": "$log_group" },
     "expression": "| stats count(*) as events_cnt by bin(5m)\r\n| filter resource_type IN [${resource_type:doublequote}]\r\n| filter event_result IN [${event_result:doublequote}]\r\n| filter event_status like /(?i)$event_status/\r\n| filter resource_name like /(?i)$resource_name/",
     "label": "Log events",
     "logGroups": [
      { "accountId": "<<ACCOUNT_ID>>", "arn": "<<LOG_GROUP_ARN>>", "name": "<<LOG_GROUP_NAME>>" }
     ],
     "metricEditorMode": 1,
     "metricName": "IncomingLogEvents",
     "namespace": "AWS/Logs",
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average",
     "statsGroups": [ "bin(5m)" ]
    }
   ]
  },
  {
   "title": "Events Messages",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expression": "fields @timestamp, resource_type, resource_name, event_status, event_result, execution_info_url, @message \n| filter resource_type IN [${resource_type:doublequote}]\n| filter event_result IN [${event_result:doublequote}]\n| filter event_status like /(?i)$event_status/\n| filter resource_name like /(?i)$resource_name/",
     "logGroups": [
      { "accountId": "<<ACCOUNT_ID>>", "arn": "<<LOG_GROUP_ARN>>", "name": "<<LOG_GROUP_NAME>>" }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average"
    }
   ]
  }
 ]
}