{
 "title": "Cloudwatch Logs with Alert Events",
 "description": "Cloudwatch logs dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "log_group", "label": "Log Group", "query": "<<LOG_GROUP_NAME>>" },
   {
    "name": "service_name",
    "label": "Service Name",
    "query": "\"step_functions\", \"glue_jobs\", \"lambda_functions\" ,\"glue_workflows\""
   },
   {
    "name": "event_severity",
    "label": "Event Severity",
    "query": "\"FAILED\", \"SUCCEEDED\", \"RUNNING\""
   },
   { "name": "search", "label": "Resource Name" }
  ]
 },
 "panels": [
  {
   "title": "Total events",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": { "LogGroupName": "<<LOG_GROUP_NAME>>" },
     "expression": "| stats count(*) \r\n| filter service_name IN [$service_name]\r\n| filter resource_name like /(?i)$search/\r\n",
     "logGroups": [
      { "accountId": "<<ACCOUNT_ID>>", "arn": "<<LOG_GROUP_ARN>>", "name": "<<LOG_GROUP_NAME>>" }
     ],
     "metricEditorMode": 1,
     "metricName": "IncomingLogEvents",
     "metricQueryType": 1,
     "namespace": "AWS/Logs",
     "queryMode": "Logs",
     "region": "default",
     "sqlExpression": "| stats count(*) by $service_name",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Events by Statuses",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 10, "x": 4, "y": 0 },
   "targets": [
    {
     "dimensions": { "LogGroupName": "<<LOG_GROUP_NAME>>" },
     "expression": "| stats count(*) as cnt by coalesce(event.detail.status, event.detail.state) \r\n| filter service_name IN [$service_name]\r\n| filter resource_name like /(?i)$search/\r\n| sort by cnt\r\n",
     "logGroups": [
      { "accountId": "<<ACCOUNT_ID>>", "arn": "<<LOG_GROUP_ARN>>", "name": "<<LOG_GROUP_NAME>>" }
     ],
     "metricEditorMode": 1,
     "metricName": "IncomingLogEvents",
     "metricQueryType": 1,
     "namespace": "AWS/Logs",
     "queryMode": "Logs",
     "region": "default",
     "sqlExpression": "| stats count(*) by $service_name",
     "statistic": "Average",
     "statsGroups": [
      "coalesce(event.detail.status",
      "event.detail.state)"
     ]
    }
   ]
  },
  {
   "title": "Events timeline",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Log events",
     "dimensions": { "LogGroupName": "$log_group" },
     "expression": "| stats count(*) by @timestamp, coalesce(event.detail.status, event.detail.state)\r\n| filter service_name IN [$service_name]\r\n| filter coalesce(event.detail.status, event.detail.state) IN [$event_severity]\r\n| filter resource_name like /(?i)$search/",
     "label": "Log events",
     "logGroups": [
      { "accountId": "<<ACCOUNT_ID>>", "arn": "<<LOG_GROUP_ARN>>", "name": "<<LOG_GROUP_NAME>>" }
     ],
     "metricEditorMode": 1,
     "metricName": "IncomingLogEvents",
     "namespace": "AWS/Logs",
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average",
     "statsGroups": [
      "@timestamp",
      "coalesce(event.detail.status",
      "event.detail.state)"
     ]
    }
   ]
  },
  {
   "title": "All Events",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expression": "fields @timestamp, service_name, resource_name, coalesce(event.detail.status, event.detail.state) as status_or_state,event_severity, @message \n| filter service_name IN [$service_name]\n| filter coalesce(event.detail.status, event.detail.state) IN [$event_severity]\n| filter resource_name like /(?i)$search/\n",
     "logGroups": [
      { "accountId": "<<ACCOUNT_ID>>", "arn": "<<LOG_GROUP_ARN>>", "name": "<<LOG_GROUP_NAME>>" }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average"
    }
   ]
  }
 ]
}