name: CDK deploy action
description: Deploy CDK app
inputs:
  cdk-folder-name:  
    description: 'where cdk app resides'
    required: true
  stage-name:  
    description: 'stage-name which is used as CDK context var'
    required: true
  cdk-bootstrap-qualifier:
    description: 'Optional bootstrap qualifier for CDK'
    required: false
    default: "" # Default value set to an empty string
    # If cdk-bootstrap-qualifier is not set or passed as an empty_string - 
    # runs cdk deploy command with default CDKToolkit, otherwise - using given alternative

runs:
  using: "composite"
  steps:
    - name: CDK deploy
      shell: bash
      run: |
        source venv/bin/activate      
        cd ${{ inputs.cdk-folder-name }}

        if [ -n "${{ inputs.cdk-bootstrap-qualifier }}" ]; then
          cdk deploy --context stage-name=${{ inputs.stage-name }} \
            --context "@aws-cdk/core:bootstrapQualifier=${{ inputs.cdk-bootstrap-qualifier }}" \
            --require-approval never
        else
          cdk deploy --context stage-name=${{ inputs.stage-name }} --require-approval never
        fi
        
