name: CDK deploy action
description: Deploy CDK app
inputs:
  cdk-folder-name:  
    description: 'where cdk app resides'
    required: true
  stage-name:  
    description: 'stage-name which is used as CDK context var'
    required: true

runs:
  using: "composite"
  steps:
    - name: CDK deploy
      shell: bash
      run: |
        source venv/bin/activate      
        cd ${{ inputs.cdk-folder-name }}
        cdk deploy --context stage-name=${{ inputs.stage-name }} --require-approval never
        
