AWSTemplateFormatVersion: '2010-09-09'
Resources:
  CdkDeployPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: policy-salmon-cdk-cloudformation-exec-all
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - cloudformation:*    # For Nested Stacks (InfraToolingMainStack)
              - ec2:*               # ToolingGrafana
              - emr-serverless:*    # ToolingAlerting, Monitored
              - events:*            # ToolingAlerting, ToolingMonitoring, Monitored
              - glue:*              # Monitored
              - kms:*               # ToolingCommon, ToolingGrafana, ToolingMonitoring
              - lambda:*            # ToolingAlerting, ToolingCommon, ToolingMonitoring, Monitored
              - logs:*              # ToolingAlerting, ToolingCommon, ToolingGrafana, Monitored
              - s3:*                # ToolingAlerting, ToolingCommon, ToolingGrafana, ToolingMonitoring
              - ses:*               # ToolingCommon
              - sns:*               # ToolingAlerting, ToolingCommon, ToolingMonitoring
              - ssm:*               # Required by CDK itself (ssm:GetParameters)
              - sqs:*               # ToolingAlerting, ToolingCommon, ToolingMonitoring
              - states:*            # Monitored
              - timestream:*        # ToolingCommon, ToolingGrafana, ToolingMonitoring
            Resource: "*"
          - Effect: Allow
            Action:           
              - iam:*               # ToolingAlerting, ToolingCommon, ToolingGrafana, ToolingMonitoring, Monitored           
              - secretsmanager:*    # ToolingCommon, ToolingGrafana           
            Resource: "arn:aws:iam::*:role/*salmon*"


Outputs:
  PolicyArn:
    Description: "The ARN of the IAM Policy policy-salmon-cdk-cloudformation-exec-all"
    Value: !Ref CdkDeployPolicy
