AWSTemplateFormatVersion: '2010-09-09'
Resources:
  CdkDeployPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: policy-salmon-cdk-cloudformation-exec-all
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - s3:*
              - sns:*
              - sqs:*
              - lambda:*
              - logs:*
              - iam:*
              - events:*
              - emr-serverless:*
              - kms:*
              - timestream:*
              - ses:*
              - secretsmanager:*
            Resource: "*"


Outputs:
  PolicyArn:
    Description: "The ARN of the IAM Policy policy-salmon-cdk-cloudformation-exec-all"
    Value: !Ref CdkDeployPolicy
