AWSTemplateFormatVersion: '2010-09-09'
Resources:
  CdkDeployPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: policy-salmon-cdk-cloudformation-exec-all
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - ec2:*               # ToolingGrafana
              - emr-serverless:*    # ToolingAlerting
              - events:*            # ToolingAlerting, ToolingMonitoring
              - iam:*               # ToolingAlerting, ToolingCommon, ToolingGrafana, ToolingMonitoring
              - kms:*               # ToolingCommon, ToolingGrafana, ToolingMonitoring
              - lambda:*            # ToolingAlerting, ToolingCommon, ToolingMonitoring
              - logs:*              # ToolingAlerting, ToolingCommon, ToolingGrafana
              - s3:*                # ToolingAlerting, ToolingCommon, ToolingGrafana, ToolingMonitoring
              - secretsmanager:*    # ToolingCommon, ToolingGrafana
              - ses:*               # ToolingCommon
              - sns:*               # ToolingAlerting, ToolingCommon, ToolingMonitoring
              - sqs:*               # ToolingAlerting, ToolingCommon, ToolingMonitoring
              - timestream:*        # ToolingCommon, ToolingGrafana, ToolingMonitoring
            Resource: "*"


Outputs:
  PolicyArn:
    Description: "The ARN of the IAM Policy policy-salmon-cdk-cloudformation-exec-all"
    Value: !Ref CdkDeployPolicy
