name: Integration tests - Execute Tests
env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_DEFAULT_REGION: 'eu-central-1'
run-name: integration tests - execute tests
on: 
  workflow_dispatch:
  workflow_call:
jobs:
  integration-testing:
    runs-on: ubuntu-latest
    steps:
        - name: Check out repository code
          uses: actions/checkout@v4

        - name: Setup Python Virtual Environment
          id: setup-venv
          uses: ./.github/actions/setup-venv          
          
        - name: Assign STAGE_NAME
          id: assign_stage_name
          uses: ./.github/actions/assign-inttest-stage-name

        - name: Install Python Test requirements
          shell: bash
          run: |
            venv/bin/pip3 install -r requirements-test.txt    
            
        - name: Set workflow start time in epoch milliseconds
          id: set_start_time
          run: echo "start_epochtimemsec=$(($(date +%s%3N)))" >> $GITHUB_ENV              
                    
        - name: Testing stand executions
          shell: bash
          run: |
            venv/bin/python integration_tests/testing_stand_execution.py --stage-name=${{ steps.assign_stage_name.outputs.STAGE_NAME }} --region=${{ env.AWS_DEFAULT_REGION }}

        # Making sure alerts have enough time to arrive
        - name: Pause for 2 minutes
          run: sleep 120

        - name: Run tests
          shell: bash
          run: |
            venv/bin/pytest integration_tests/tests --start-epochtimemsec=${{ env.start_epochtimemsec }} --stage-name=${{ steps.assign_stage_name.outputs.STAGE_NAME }} --region=${{ env.AWS_DEFAULT_REGION }}            