name: Integration tests - Full Workflow
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
run-name: integration tests - full
on: 
    push:
        branches:
          - main    
    workflow_dispatch:
jobs:
    job-create-infra:
        uses: ./.github/workflows/integration_tests_infra_create.yml
        secrets: inherit

    job-execute-tests:
        uses: ./.github/workflows/integration_tests_execute.yml
        needs: job-create-infra
        secrets: inherit

    job-delete-infra:
        uses: ./.github/workflows/integration_tests_infra_delete.yml
        needs: job-execute-tests
        secrets: inherit        