name: Integration tests - Delete Infra
env:
    CDK_INTEGRATION_TESTS_FOLDER: cdk/integration_testing_stand
    CDK_TOOLING_ENV_FOLDER: cdk/tooling_environment
    CDK_MONITORED_ENV_FOLDER: cdk/monitored_environment
    SETTING_FOLDER_NAME: "tests/integration-tests/settings"
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout      
run-name: integration tests - delete infra
on: 
  workflow_dispatch:
  workflow_call:
jobs:
  integration-testing-delete-infra:
    runs-on: ubuntu-latest
    steps:
        - name: Check out repository code
          uses: actions/checkout@v4

        - name: Assume AWS Role
          uses: ./.github/actions/assume-aws-service-role-for-tests
          with:
            aws-region: ${{ secrets.AWS_REGION }}
            account-id: ${{ secrets.AWS_ACCOUNT_ID }}    

        - name: Setup Python Virtual Environment
          id: setup-venv
          uses: ./.github/actions/setup-venv          
          
        - name: Assign STAGE_NAME
          id: assign_stage_name
          uses: ./.github/actions/assign-inttest-stage-name          

        - name: prepare CDK
          uses: ./.github/actions/cdk-prepare
          with:
            cdk-folder-name: ${{ env.CDK_INTEGRATION_TESTS_FOLDER }}
            settings-folder-name: ${{ env.SETTING_FOLDER_NAME }}
            stage-name: ${{ steps.assign_stage_name.outputs.STAGE_NAME }}
            region: ${{ secrets.AWS_REGION }}

        # 1. Destroy Monitored env
        - name: destroy monitored infra via CDK
          uses: ./.github/actions/cdk-destroy
          with:
            cdk-folder-name: ${{ env.CDK_MONITORED_ENV_FOLDER }}
            stage-name: ${{ steps.assign_stage_name.outputs.STAGE_NAME }}                 

        # 2. Destroy IntegrTests stack
        - name: destroy integration tests infra via CDK
          uses: ./.github/actions/cdk-destroy
          with:
            cdk-folder-name: ${{ env.CDK_INTEGRATION_TESTS_FOLDER }}
            stage-name: ${{ steps.assign_stage_name.outputs.STAGE_NAME }}
              
        # 3. Destroy Tooling env
        - name: destroy tooling infra via CDK
          uses: ./.github/actions/cdk-destroy
          with:
            cdk-folder-name: ${{ env.CDK_TOOLING_ENV_FOLDER }}
            stage-name: ${{ steps.assign_stage_name.outputs.STAGE_NAME }}            





