name: Testing stage name
env:
    AWS_ACCESS_KEY_ID: dummy_value
    AWS_SECRET_ACCESS_KEY: dummy_value
    AWS_DEFAULT_REGION: 'eu-central-1'    
    TESTS_FOLDER: tests
run-name: Testing stage name
on:
  workflow_dispatch:
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Assign STAGE_NAME
        id: assign_stage_name
        uses: ./.github/actions/assign-inttest-stage-name

      - name: Output STAGE_NAME
        run: echo "STAGE_NAME is ${{ steps.assign_stage_name.outputs.STAGE_NAME }}"