name: Testing stage name
env:
    AWS_ACCESS_KEY_ID: dummy_value
    AWS_SECRET_ACCESS_KEY: dummy_value
    AWS_DEFAULT_REGION: 'eu-central-1'    
    TESTS_FOLDER: tests
run-name: Testing stage name
on:
  workflow_dispatch:
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Get sanitized STAGE_NAME
        id: get_stage_name
        shell: bash
        run: |
            echo ${GITHUB_ACTOR}
            STAGE_NAME="devit${GITHUB_ACTOR:0:3}"
            echo "STAGE_NAME=$STAGE_NAME" >> $GITHUB_ENV
            # Output the resulting STAGE_NAME to the console
            echo "STAGE_NAME is $STAGE_NAME"