name: test oidc
env:
    AWS_REGION: 'eu-central-1'
    CDK_INTEGRATION_TESTS_FOLDER: cdk/integration_testing_stand
    CDK_TOOLING_ENV_FOLDER: cdk/tooling_environment
    CDK_MONITORED_ENV_FOLDER: cdk/monitored_environment
    SETTING_FOLDER_NAME: "tests/integration-tests/settings"
run-name: test oidc
on: 
  workflow_dispatch:
  workflow_call:
jobs:
  integration-testing-create-infra:
    runs-on: ubuntu-latest
    steps:
        - name: Check out repository code
          uses: actions/checkout@v4

        - name: Assume AWS Role
          uses: ./.github/actions/assume-aws-service-role-for-tests
          with:
            aws-region: ${{ env.AWS_REGION }}
            account-id: ${{ secrets.AWS_ACCOUNT_ID }}    

