name: CDK Demo
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
  AWS_DEFAULT_REGION: 'eu-central-1'
  CDK_APP_FOLDER: infra_tooling_account
run-name: test pipeline 
on: [push, workflow_dispatch]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup Node.js env
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: npm install aws-cdk
        run: npm i -g aws-cdk        

      - name: Install Python requirements
        run: |
          cd ${{ env.CDK_APP_FOLDER }}
          pip3 install -r requirements.txt        
        
      - name: Prepare replacements.json (put actual AWS account)
        run: python tests/devci_settings/prepare_replacements.py

      - name: Copy devci settings
        run: mkdir -p config/settings && cp tests/devci_settings/*.json config/settings/

      - name: Check replacements.json content
        run: cat config/settings/replacements.json

      - name: CDK deploy
        run: |
          cd ${{ env.CDK_APP_FOLDER }}
          cdk deploy --require-approval never
        


      